server:
  port: 8086
  servlet:
    context-path: /api/plumemo-service
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/hrm_db3?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#关于MyBatis-Plus的设置
mybatis-plus:
  # 别名扫描路径。这样Mapper.xml中的每个语句的resultType就不用写全路径了（但我还是习惯写全路径，尤其类很多的时候，不看路径不知道谁是谁）
  type-aliases-package: com.smart.plumemo_template.demo.*.dao

  # Mapper.xml扫描路径。然后在Mapper接口写上自定义方法并关联XML语句，即可实现手写SQL
  mapper-locations: classpath*:mapper/*/*.xml

  # MyBatis-Plus驼峰转换，配置后不论手写SQL还是接口方法，都能自动映射（默认on）
  configuration:
    map-underscore-to-camel-case: true
    #二级缓存
    cache-enabled: true
  # 全局设置：主键生成策略、逻辑删除字段
  global-config:
    db-config:
      #数据库id自增
      id-type: auto
      #全局逻辑删除字段值
      logic-delete-field: deleted
      #数据库大写下划线转换
      capital-mode: false
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0